package domain;
// Generated Jan 20, 2010 12:31:25 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Authorities generated by hbm2java
 */
@Entity
@Table(name="authorities"
    ,catalog="catalog"
)
public class Authority  implements java.io.Serializable {


     private int id;
     private String authority;
     private Date created;
     private Date modified;
     private Set<Grupa> groups = new HashSet<Grupa>(0);

    public Authority() {
    }

    public Authority(int id, Set<Grupa> groups, String authority, Date created, Date modified) {
       this.id = id;
       this.groups = groups;
       this.authority = authority;
       this.created = created;
       this.modified = modified;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="authority", nullable=false)
    public String getAuthority() {
        return this.authority;
    }
    
    public void setAuthority(String authority) {
        this.authority = authority;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", nullable=false, length=19)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modified", nullable=false, length=19)
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }

    @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="groups")
    public Set<Grupa> getGroups() {
        return this.groups;
    }

    public void setGroups(Set<Grupa> groups) {
        this.groups = groups;
    }



}


