package domain;
// Generated Jan 20, 2010 12:31:25 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Groups generated by hbm2java
 */
@Entity
@Table(name="groups"
    ,catalog="catalog"
)
public class Grupa  implements java.io.Serializable {


     private int id;
     private Authority authoritieses;
     private String name;
     private Date created;
     private Date modified;
     private Set<User> userses = new HashSet<User>(0);

    public Grupa() {
    }

	
    public Grupa(int id, String name, Date created, Date modified) {
        this.id = id;
        this.name = name;
        this.created = created;
        this.modified = modified;
    }
    public Grupa(int id, Authority authoritieses, String name, Date created, Date modified, Set<User> userses) {
       this.id = id;
       this.authoritieses = authoritieses;
       this.name = name;
       this.created = created;
       this.modified = modified;
       this.userses = userses;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="authority_id", nullable=false)
    public Authority getAuthoritieses() {
        return this.authoritieses;
    }

    public void setAuthoritieses(Authority authoritieses) {
        this.authoritieses = authoritieses;
    }

    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", nullable=false, length=19)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modified", nullable=false, length=19)
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="groups")
    public Set<User> getUserses() {
        return this.userses;
    }
    
    public void setUserses(Set<User> userses) {
        this.userses = userses;
    }




}


