package domain;
// Generated Jan 20, 2010 12:31:25 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Rangies generated by hbm2java
 */
@Entity
@Table(name="rangies"
    ,catalog="catalog"
)
public class Range  implements java.io.Serializable {


     private int id;
     private String name;
     private Date created;
     private Date modified;
     private Set<User> userses = new HashSet<User>(0);

    public Range() {
    }

	
    public Range(int id, String name, Date created, Date modified) {
        this.id = id;
        this.name = name;
        this.created = created;
        this.modified = modified;
    }
    public Range(int id, String name, Date created, Date modified, Set<User> userses) {
       this.id = id;
       this.name = name;
       this.created = created;
       this.modified = modified;
       this.userses = userses;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", nullable=false, length=19)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modified", nullable=false, length=19)
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="usersrangies", catalog="catalog", joinColumns = { 
        @JoinColumn(name="range_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="user_id", nullable=false, updatable=false) })
    public Set<User> getUserses() {
        return this.userses;
    }
    
    public void setUserses(Set<User> userses) {
        this.userses = userses;
    }


    @Override
    public String toString() {
        return this.name;
    }
}


