package domain;
// Generated Jan 20, 2010 12:31:25 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users"
    ,catalog="catalog"
)
public class User  implements java.io.Serializable {


     private int id;
     private Grupa groups;
     private String username;
     private String firstname;
     private String lastname;
     private String password;
     private String confirmpassword;
     private String email;
     private Date created;
     private Date modified;
     private int enabled;
     private Set<Range> rangieses = new HashSet<Range>(0);

    public User() {
    }

	
    public User(int id, Grupa groups, String username, String firstname, String lastname, String password, String email, Date created, Date modified, int enabled) {
        this.id = id;
        this.groups = groups;
        this.username = username;
        this.firstname = firstname;
        this.lastname = lastname;
        this.password = password;
        this.email = email;
        this.created = created;
        this.modified = modified;
        this.enabled = enabled;
    }
    public User(int id, Grupa groups, String username, String firstname, String lastname, String password, String email, Date created, Date modified, int enabled, Set<Range> rangieses) {
       this.id = id;
       this.groups = groups;
       this.username = username;
       this.firstname = firstname;
       this.lastname = lastname;
       this.password = password;
       this.email = email;
       this.created = created;
       this.modified = modified;
       this.enabled = enabled;
       this.rangieses = rangieses;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="group_id", nullable=false)
    public Grupa getGroups() {
        return this.groups;
    }
    
    public void setGroups(Grupa groups) {
        this.groups = groups;
    }
    
    @Column(name="username", nullable=false)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    
    @Column(name="firstname", nullable=false)
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    
    @Column(name="lastname", nullable=false)
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    
    @Column(name="password", nullable=false)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    @Column(name="confirmpassword", nullable=false)
    public String getConfirmpassword() {
        return this.confirmpassword;
    }

    public void setConfirmpassword(String password) {
        this.confirmpassword = password;
    }

    @Column(name="email", nullable=false)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", nullable=false, length=19)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modified", nullable=false, length=19)
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
    
    @Column(name="enabled", nullable=false)
    public int getEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(int enabled) {
        this.enabled = enabled;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="usersrangies", catalog="catalog", joinColumns = { 
        @JoinColumn(name="user_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="range_id", nullable=false, updatable=false) })
    public Set<Range> getRangieses() {
        return this.rangieses;
    }
    
    public void setRangieses(Set<Range> rangieses) {
        this.rangieses = rangieses;
    }

}


